### PR TITLE
server: templates can hold raw rules for simplicity

### PR DESCRIPTION
**Pull request by xvello**
Most of our templates are only using boolean params to add/remove simple rules. The handlebars templating + tests can become tedious and does not add value for these templates.

This PR allows template contributors to add a `rules` field to boolean params, and skip the `template` and `tests` sections. This mechanism is only supported if ALL params are boolean and have rules specified.

I'll need to add more backend tests before merging, but I wanted to get the idea out there first.

### CODE REVIEW

**Comment by xvello** [comment]
Heya @letsblockit/contributors, I'd love your feedback on this change: will it make maintenance easier, or be confusing by having two ways to define rules (inline, and in a `template`)?

Check [how the fandom-cleanup](https://github.com/letsblockit/letsblockit/pull/585/files#diff-8ad1944c806700d8579bf85fcb6f5b756dde3c5381cb0c10f220ff411927583d) template is shorter. I went with multiline strings for `rules`, even when there was a single line, to make sure that we don't get in to unescaped quote issues one day.

**Review by JohnyP36 — APPROVED** [review]
As you have done with [`the shortened Fandom cleanup template`](https://github.com/letsblockit/letsblockit/pull/585/files#diff-8ad1944c806700d8579bf85fcb6f5b756dde3c5381cb0c10f220ff411927583d) I like it better, as it saves time double checking if every thing/rule is on place. 
The only thing we have to check is if the whole template only contains check-mark rule, but that's way easier than copy-pasting several parts of the template (you always must be cautious to copy the rules section to the same position in the test section).

**Comment by xvello** [comment]
Thanks for the feedback!

> The only thing we have to check is if the whole template only contains check-mark rule

It's automatically checked by the template parsing system. A template much have either but not both of:
- a top-level template field
- every param of checkbox type with rules

**Comment by JohnyP36** [comment]
> Thanks for the feedback!

>  >   The only thing we have to check is if the whole template only contains check-mark rule

Does this mean we can have two types of templates, one with your newly proposed changes and one like the old templates (if the requirements are not met)?

**Review by Nomes77 — APPROVED** [review]

**Comment by xvello** [comment]
Thanks for your feedback! I'm merging this and crossing fingers I'm not breaking a template.

Feel free to port the eligible templates to this new syntax if you have a moment. I recommend:
  - first pushing a commit that keeps the `tests` section and have the CI run, to make sure rules are moved under the right option
  - after the CI is green, push a second commit to remove the tests

**Pull request merged**
