### PR TITLE
search-results: add DuckDuckGo and Brave .onion

### PR DESCRIPTION
**Pull request by BPower0036**
Added DuckDuckGo and Brave .onion addresses

### CODE REVIEW

**Review by JohnyP36 — CHANGES_REQUESTED** [review]
As I guess most people don't use .onion websites, is it thus not better to clone this template and made something like `search-results-onion`?

**Comment by BPower0036** [comment]
@JohnyP36 In my opinion the search-results list should remain one. A list for only two .onion domains is a little short in my opinion.

**Comment by xvello** [comment]
Thanks for jumping into this @BPower0036. I agree that it makes sense to keep it in the same template. Merging your PR as is would increase the number of rules we generate (and the computing cost to load these on browser startup), but won't affect the performance when loading the websites, as the rules are scoped to a domain.

If we don't want to double the rules for a pretty small portion of users, I suggest adding a sub-option like we currently have for the other ddg flavors. 

image

This way, it's a no-op for people who don't use the onion websites. WDYT?

**Comment by BPower0036** [comment]
@xvello I agree on making a suboption.

**Comment by BPower0036** [comment]
@xvello It looks like the GitHub-actions fail, because it can't verify the `.onion` addresses.

**Review by xvello — APPROVED** [review]
This field expects a full url with the `https://` scheme, which is OK for Tor links too. I just tested it.

**Comment by xvello** [comment]
FYI, I added https://github.com/letsblockit/letsblockit/commit/d5a722ce7a955d03bb5474288f3e5c63e6eec4f9: a DB migration to not mark the template updated for these new options. As they are sub-options, it will be confusing to users that don't had DDG/brave enabled already, as the sub-options won't show up in the form.

**Pull request merged**
