### PR TITLE
youtube-cleanup: update copyright-notice rule for new layout

### PR DESCRIPTION
**Pull request by JohnyP36**
copyright-notice: the other rule does not exist anymore

<details><summary>Working rule print-screen</summary>

afbeelding

</details> 

<details><summary>NOT working rule print-screen</summary>

afbeelding

</details>

### CODE REVIEW

**Review by xvello — APPROVED** [review]
Thanks a lot!

**Comment by xvello** [comment]
@JohnyP36 could you please also update the fifth test case, at the bottom of the file?

You can check what tests are failing by clicking on "Details" and checking the bottom of the logs.
image

**Comment by JohnyP36** [comment]
> @JohnyP36 could you please also update the fifth test case, at the bottom of the file?
> 
> You can check what tests are failing by clicking on "Details" and checking the bottom of the logs. image

afbeelding

**Comment by JohnyP36** [comment]
@xvello solved error

**Review by xvello — APPROVED** [review]

**Pull request merged**
