### PR TITLE
search-results: re-introduce support for Bing

### PR DESCRIPTION
**Pull request by BPower0036**
You recently removed Bing from the search-result.
I had some time, so now I made them working again for the web, image, video and news pages of Bing

### CODE REVIEW

**Comment by xvello** [comment]
Heya @BPower0036!

The `:has-text()` option was discussed in https://github.com/letsblockit/letsblockit/issues/430 and https://github.com/quenhus/uBlock-Origin-dev-filter/issues/374#issuecomment-1491723910, and neither quentus nor I think we should use that slow selector, especially in a template that will be used with hundreds of input values.

Thanks for looking into it, but I think it's still better to direct people to ublacklist instead of shipping a very slow template.

**Comment by JohnyP36** [comment]
> @xvello 
> ... a very slow template

Although it's slower than using `:upward()`, the difference in responsiveness is not really large. I think we are speaking of a difference of a couple of milliseconds. 

**But** since we already directed people to ublacklist we should be consistent and stick with the decision - so users will not be/get confused.

**Comment by BPower0036** [comment]
@xvello I just added Bing back to show that is could be working. Furthermore, the `:has-text()` option is very precise. If you think  ublacklist is better this PR can be closed

**Review by xvello — APPROVED** [review]
Sorry for the delay here, let's release it!

**Pull request merged**
