### PR TITLE
Twitter Cleanup (see https://github.com/letsblockit/letsblockit/issues/269)

### PR DESCRIPTION
**Pull request by JohnyP36**
I did not check those rules. Just copied them from https://www.reddit.com/r/uBlockOrigin/wiki/solutions#wiki_twitter. 

Note: some descriptions are vague and need improvement.

### CODE REVIEW

**Comment by BPower0036** [comment]
I changed the YT file, because we already have a "remove redundant/old rules" for Youtube.

**Comment by xvello** [comment]
Hello @JohnyP36, thanks for your contribution!

Sorry for not reviewing this earlier: life got in the way this week, and I'll be out of town until Monday.

> I did not check those rules

As I wrote in https://github.com/letsblockit/letsblockit/issues/269, my main worry is the  ongoing maintenance, not the initial work. My target is for us to be able to proactively update the template when needed (like you and @BPower0036 do well for youtube), not react to users signaling breakages. I prefer quality over quantity for the time being.

I expect the Twitter interface to move a lot in the upcoming months, that's why I left the issue open in search of a regular Twitter user to step in. Not testing the rules signals to me that you might not be the best person to take over the ongoing maintenance burden. How do you feel about that?

**Comment by JohnyP36** [comment]
> I expect the Twitter interface to move a lot in the upcoming months, that's why I left the issue open in search of a regular Twitter user to step in. Not testing the rules signals to me that you might not be the best person to take over the ongoing maintenance burden. How do you feel about that?

I made the file, in order to help the person who wants to maintain the rules. 
I'm indeed not the right person for this. Thus I hope someone else can maintain those rules.

As long there is no person, keep this PR open.

**Comment by xvello** [comment]
Heya @JohnyP36, as this is new template there's no need to rebase it regularly. I'm converting to draft to convey the current state of this work: we're not ready to merge it until someone steps up as maintainer.

**Comment by xvello** [comment]
Closing alongside https://github.com/letsblockit/letsblockit/issues/269, I think there are better uses of our energy.

**Pull request closed without merging**
