### PR TITLE
youtube-video-title: improve word matching

### PR DESCRIPTION
**Pull request by JohnyP36**
See https://github.com/letsblockit/letsblockit/issues/347 (Hide Youtube videos by title should look for other separators if possible)

I changed every `~` for `*`.

### CODE REVIEW

**Comment by JohnyP36** [comment]
Because of the discussion in #347 

I propose the following: 

1. keep this file as it was - to avoid false positives
<details><summary>this way</summary>

```yaml
title: Hide Youtube videos by title
params:
  - name: keywords
    description: Words to search for
    type: list
    default: [ "lofi", "#shorts" ]
tags:
  - youtube
template: |
  {{#each keywords}}
  www.youtube.com##ytd-browse ytd-grid-video-renderer:has(#video-title[title~="{{ . }}" i])
  www.youtube.com##ytd-browse ytd-rich-item-renderer:has(#video-title-link[title~="{{ . }}" i])
  www.youtube.com##ytd-search ytd-video-renderer:has(#video-title[title~="{{ . }}" i])
  www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-compact-video-renderer:has(#video-title[title~="{{ . }}" i])
  {{! Subscriptions in list mode, hide the whole section as subsequent videos from same channel are currently pushed in separate sections }}
  www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-video-renderer #video-title[title~="{{ . }}" i]:upward(ytd-item-section-renderer)
  {{/each}}
tests:
  - params: {}
    output: ""
  - params:
      keywords: [ "lofi", "#shorts" ]
    output: |
      www.youtube.com##ytd-browse ytd-grid-video-renderer:has(#video-title[title~="lofi" i])
      www.youtube.com##ytd-browse ytd-rich-item-renderer:has(#video-title-link[title~="lofi" i])
      www.youtube.com##ytd-search ytd-video-renderer:has(#video-title[title~="lofi" i])
      www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-compact-video-renderer:has(#video-title[title~="lofi" i])
      www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-video-renderer #video-title[title~="lofi" i]:upward(ytd-item-section-renderer)
      www.youtube.com##ytd-browse ytd-grid-video-renderer:has(#video-title[title~="#shorts" i])
      www.youtube.com##ytd-browse ytd-rich-item-renderer:has(#video-title-link[title~="#shorts" i])
      www.youtube.com##ytd-search ytd-video-renderer:has(#video-title[title~="#shorts" i])
      www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-compact-video-renderer:has(#video-title[title~="#shorts" i])
      www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-video-renderer #video-title[title~="#shorts" i]:upward(ytd-item-section-renderer)
---

Not everything on the platform matches your interests, and the famous algorithm is not that great at understanding this. With this filter, you can remove videos with a given word in their title.

<div class="alert alert-warning" role="alert">
In order to reduce false-positives, the filter matches full words (with spaces around them, or at the start/end of the title). It does a case-insensitive match though (`lofi` will also match `LoFi`).
</div>
```

</details>

2. Add a new template, which is aggressive
<details><summary>what I changed in the original file</summary>

```yaml
title: Hide Youtube videos by title
params:
  - name: keywords
    description: Words to search for
    type: list
    default: [ "lofi", "#shorts" ]
tags:
  - youtube
template: |
  {{#each keywords}}
  www.youtube.com##ytd-browse ytd-grid-video-renderer:has(#video-title[title*="{{ . }}" i])
  www.youtube.com##ytd-browse ytd-rich-item-renderer:has(#video-title-link[title*="{{ . }}" i])
  www.youtube.com##ytd-search ytd-video-renderer:has(#video-title[title*="{{ . }}" i])
  www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-compact-video-renderer:has(#video-title[title*="{{ . }}" i])
  {{! Subscriptions in list mode, hide the whole section as subsequent videos from same channel are currently pushed in separate sections }}
  www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-video-renderer #video-title[title*="{{ . }}" i]:upward(ytd-item-section-renderer)
  {{/each}}
tests:
  - params: {}
    output: ""
  - params:
      keywords: [ "lofi", "#shorts" ]
    output: |
      www.youtube.com##ytd-browse ytd-grid-video-renderer:has(#video-title[title*="lofi" i])
      www.youtube.com##ytd-browse ytd-rich-item-renderer:has(#video-title-link[title*="lofi" i])
      www.youtube.com##ytd-search ytd-video-renderer:has(#video-title[title*="lofi" i])
      www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-compact-video-renderer:has(#video-title[title*="lofi" i])
      www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-video-renderer #video-title[title*="lofi" i]:upward(ytd-item-section-renderer)
      www.youtube.com##ytd-browse ytd-grid-video-renderer:has(#video-title[title*="#shorts" i])
      www.youtube.com##ytd-browse ytd-rich-item-renderer:has(#video-title-link[title*="#shorts" i])
      www.youtube.com##ytd-search ytd-video-renderer:has(#video-title[title*="#shorts" i])
      www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-compact-video-renderer:has(#video-title[title*="#shorts" i])
      www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-video-renderer #video-title[title*="#shorts" i]:upward(ytd-item-section-renderer)
---

Not everything on the platform matches your interests, and the famous algorithm is not that great at understanding this. With this filter, you can remove videos with a given word in their title.

<div class="alert alert-warning" role="alert">
This template is very aggressive and also blocks part of words).
</div>
```

</details>

**Comment by xvello** [comment]
Heya @JohnyP36, thanks for jumping into this!

I agree that `*=` is too aggressive and will lead to false-positives. In [youtube-cleanup.yaml](https://github.com/letsblockit/letsblockit/blob/6d3e821f22d1646bf05fe6c8cdf13838cbdc801b/data/filters/templates/youtube-cleanup.yaml#L64) we use the `\b` regexp operator to detect word boundaries, what do you think about this? It should match the examples from the issues, without matching on parts of longer words.

There is a slight performance penalty though, but we can amortize it later on by building a single regexp with all the words, instead of one set of rules per word

**Comment by JohnyP36** [comment]
> Heya @JohnyP36, thanks for jumping into this!
> 
> I agree that `*=` is too aggressive and will lead to false-positives. In [youtube-cleanup.yaml](https://github.com/letsblockit/letsblockit/blob/6d3e821f22d1646bf05fe6c8cdf13838cbdc801b/data/filters/templates/youtube-cleanup.yaml#L64) we use the `\b` regexp operator to detect word boundaries, what do you think about this? It should match the examples from the issues, without matching on parts of longer words.
> 
> There is a slight performance penalty though, but we can amortize it later on by building a single regexp with all the words, instead of one set of rules per word

<details><summary>You mean doing this?</summary>

```yaml
title: Hide Youtube videos by title
params:
  - name: keywords
    description: Words to search for
    type: list
    default: [ "lofi", "#shorts" ]
tags:
  - youtube
template: |
  {{#each keywords}}
  www.youtube.com##ytd-browse ytd-grid-video-renderer:has(#video-title[title]:has-text(/\b{{this}}\b/i))
  www.youtube.com##ytd-browse ytd-rich-item-renderer:has(#video-title-link[title]:has-text(/\b{{this}}\b/i))
  www.youtube.com##ytd-search ytd-video-renderer:has(#video-title[title]:has-text(/\b{{this}}\b/i))
  www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-compact-video-renderer:has(#video-title[title]:has-text(/\b{{this}}\b/i))
  {{! Subscriptions in list mode, hide the whole section as subsequent videos from same channel are currently pushed in separate sections }}
  www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-video-renderer #video-title[title]:has-text(/\b{{this}}\b/i):upward(ytd-item-section-renderer)
  {{/each}}
tests:
  - params: {}
    output: ""
  - params:
      keywords: [ "lofi", "#shorts" ]
    output: |
      www.youtube.com##ytd-browse ytd-grid-video-renderer:has(#video-title[title]:has-text(/\blofi\b/i))
      www.youtube.com##ytd-browse ytd-rich-item-renderer:has(#video-title-link[title]:has-text(/\blofi\b/i))
      www.youtube.com##ytd-search ytd-video-renderer:has(#video-title[title]:has-text(/\blofi\b/i))
      www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-compact-video-renderer:has(#video-title[title]:has-text(/\blofi\b/i))
      www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-video-renderer #video-title[title]:has-text(/\blofi\b/i):upward(ytd-item-section-renderer)
      www.youtube.com##ytd-browse ytd-grid-video-renderer:has(#video-title[title]:has-text(/\b#shorts\b/i))
      www.youtube.com##ytd-browse ytd-rich-item-renderer:has(#video-title-link[title]:has-text(/\b#shorts\b/i))
      www.youtube.com##ytd-search ytd-video-renderer:has(#video-title[title]:has-text(/\b#shorts\b/i))
      www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-compact-video-renderer:has(#video-title[title]:has-text(/\b#shorts\b/i))
      www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-video-renderer #video-title[title]:has-text(/\b#shorts\b/i):upward(ytd-item-section-renderer)
---

Not everything on the platform matches your interests, and the famous algorithm is not that great at understanding this. With this filter, you can remove videos with a given word in their title.

<div class="alert alert-warning" role="alert">
In order to reduce false-positives, the filter matches full words (with spaces around them, or at the start/end of the title). It does a case-insensitive match though (`lofi` will also match `LoFi`).
</div>
```

</details>

#### Note: 
 - I changed every `{{ . }}` in `{{this}}`. I don't know if that's correct,  
 but in the other template `{{this}` is used and not `{{ . }}`
 - I only checked the rule for the homepage of YouTube and it worked. *(2nd rule in template)*

**Comment by xvello** [comment]
Indeed! ` {{ . }}` and `{{this}}` are equivalent in handlebars BTW.

**Comment by JohnyP36** [comment]
I changed the template and checked all the rules. It is working.
So, you can merge it, if you want

**Review by xvello — APPROVED** [review]
Thanks a lot @JohnyP36!

Although we don't explicitly support it, individual rules will break if the user adds one of the special regex characters: `.*+?^${}()|[]\`. See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) for the full list.

We should escape these special characters with a `\`, but this is better handled on the golang side than in the template itself. I'll do a follow-up PR to implement it this weekend. It will be useful to other templates too, and we might be able to support a mix of words and regex from the user.

**Comment by xvello** [comment]
Heya @JohnyP36 thanks a lot for your many contributions!

I invited you to the @letsblockit/contributors team, which means that you'll be able to push your work branches directly on this repo instead of keeping a fork in sync. Please give a descriptive name to your branches (I like to use the `$name/$feature` convention [on my branches](https://github.com/letsblockit/letsblockit/branches)), so that it's easier to track them.

This also gives your access to triage, label and close issues and PR, but please refrain from any harsh action and ping me if you have any question.

**Pull request merged**
