### PR TITLE
display contributors and sponsors in the app

### PR DESCRIPTION
**Pull request by xvello**
- Display in each template sidebar:
    - template contributors, defined as:
      - contributing rules, either via a PR or in an issue (even if they were reworked before inclusion)
      - improvements to the descriptions (excluding typos)
      - contributing presets
    - sponsors in the "adopt a template" tier

image

- Display all contributors on the landing page (seen by logged-out users)

image

The avatars are shipped with the server in 96px size (twice the display size, for retina displays), and allowed to be cached on browsers for a week (unless modified in the meantime).

- Display all contributors on the about page:

image

I'd like to add more, including:

  - a list of all financial contributors, initially put in the template list sidebar, but that might become too big over time

### CODE REVIEW

**Comment by xvello** [comment]
Heya @letsblockit/contributors!

I deployed this PR at https://staging.letsblock.it and would love your feedback on it. More info in the PR description.

**Review by JohnyP36 — APPROVED** [review]
@xvello I'm oké with it. Although it's not clear if logged-out users (as me) can also see the template sponsors and maintainers. That would be nice.

**Comment by xvello** [comment]
Thanks @JohnyP36. Logged-out users are served the same sidebar, so they'll see contributors and sponsors, like logged-in users.
You can test that by opening a private browser window and going to https://staging.letsblock.it/filters/search-results

I'm having second-thoughts about adding all sponsors to the https://staging.letsblock.it/filters page, which might grow pretty big over time. I'm leaning towards removing it for now. One-time sponsors will still be listed in the full contributor list.

**Comment by JohnyP36** [comment]
@xvello It's working. But I am wondering how the website knows who contributed to which template. 
As you can see, I helped on the [Google Search: interface cleanups](https://github.com/letsblockit/letsblockit/pull/398), but my avatar is not displayed on the website/app as it only says that you are a contributor (See https://letsblock.it/filters/google-search-cleanup)

**Comment by xvello** [comment]
Heya @JohnyP36,

The source for these avatars is the new `contributors` field in the yaml file, such as [this example](https://github.com/letsblockit/letsblockit/blob/89fb095d73508508b99c0ccb951d43c191a9f744/data/filters/templates/youtube-video-title.yaml#L2-L4):
  - the value is a list, let's keep these lists alphabetically sorted for easier maintenance
  - the value should match the `login` property in the [contributors.json](https://github.com/letsblockit/letsblockit/blob/main/data/contributors.json) file, and there's a check to make sure there's a match
  - to add more people to the contributors.json file, you can manually trigger [the add contributor workflow](https://github.com/letsblockit/letsblockit/actions/workflows/add-contributor.yml), passing the github username, and the contribution type.

I need to add more documentation about all this, this weekend.

I'm sorry I missed some contributions, and we should fix that. I read 18 months of git commits to populate that data manually, by checking the commit authors and people listed in the `Co-authored-by` header (like in [this commit](https://github.com/letsblockit/letsblockit/commit/0daf0fb068db14c512766fdadd2eeea63ff46804)). While I try to be diligent with adding this `Co-authored-by` header, I most probably forgotten some. I also chose not to list people I credited in `Co-authored-by`, but only contributed an idea and not the rules. I'm happy to go back on that decision BTW.

Please open a branch to fix the templates that don't credit you, I'll be happy to merge it ASAP. Don't hesitate to also add anyone else I have forgotten: I should have taken the time to triple-check this data, but currently time is in short supply on my end :/

**Comment by JohnyP36** [comment]
> I also chose not to list people I credited in Co-authored-by, but only contributed an idea and not the rules. I'm happy to go back on that decision BTW.

In the case I was mentioning `@3DWORX-SA` opened an issue with an idea/question, but I *(and you off course)* made the rules. So, I thing it is fair to also include `Co-authored-by` as I - or every other person who makes rules on behave of someone's ideas - are contributing to that template.

**Comment by xvello** [comment]
> In the case I was mentioning @3DWORX-SA opened an issue with an idea/question, but I (and you off course) made the rules. So, I thing it is fair to also include Co-authored-by as I - or every other person who makes rules on behave of someone's ideas - are contributing to that template.

Thanks for checking this, and opening the PR to fix it! *As per the criteria I listed, I'd rather you only add yourself, could you please update that?* While people contributing ideas and testing help move the project forward and are listed in the main contributor list, the per-template list is intended as a "badge of honor" for people who contribute rules.

FYI, I will not rewrite the git history to add you as co-author on this commit, because:
- it breaks forks and release tags
- it is frowned upon as a bad practice, as rewriting history can be used to hide bad code in older commits

I do sometimes rewrite the latest commit when I'm working on the CI (because most of the time you can only test these from the main branch), but as a rule never rewrite history deeper than the latest commit.

Github's handling of the `Co-authored-by` header is clunky and inconsistent (people are credited in [the insights](https://github.com/letsblockit/letsblockit/graphs/contributors) but not the project's sidebar), that's why I'm phasing it out in favor of this `contributors` metadata field. Having that field also allows us to fix attribution mistakes without rewriting the git history.

Don't hesitate to ask if anything does not feel clear, I really don't want to have miscommunications on that topic.

**Comment by 3DWORX-SA** [comment]
Thanks, but I would prefer to remain anonymous.

**Comment by JohnyP36** [comment]
@xvello Thanks for explaining. It's clear now for me and I changed my PR. Thanks a lot.

**Pull request merged**
