### PR TITLE
youtube-cleanup: remove outdated rules targeting old design

### PR DESCRIPTION
**Pull request by JohnyP36**
See [#292 (comment)](https://github.com/letsblockit/letsblockit/pull/292#issuecomment-1302242114)

### CODE REVIEW

**Comment by BPower0036** [comment]
`##.ytd-watch-metadata > .top-level-buttons #text:not(:has-text(/[\d]/))` is the second newest design. If could be possible that not everyone has the newest design.
Thus, it would be save to keep that rule for a moment.

You made a duplicate of https://github.com/letsblockit/letsblockit/pull/293 so I hope you don't mind I'm closing this PR

**Comment by JohnyP36** [comment]
> `##.ytd-watch-metadata > .top-level-buttons #text:not(:has-text(/[\d]/))` is the second newest design. If could be possible that not everyone has the newest design. Thus, it would be save to keep that rule for a moment.
> 
> You made a duplicate of #293 so I hope you don't mind I'm closing this PR

He asked me to do it. NOT you.

**Comment by BPower0036** [comment]
@JohnyP36 I'm sorry, but I saw his question. Plus I removed more from the old-old YoutTube design.

**Comment by xvello** [comment]
Heya @JohnyP36, @BPower0036.Thank you both for your quick response! It's unfortunate that you duplicated work, and I'm sorry about that!

I do agree that it's probably better to keep the "old-new" rules for now, as I'm not sure that the new layout has been rolled out to all countries. Checking the [git blame for this file](https://github.com/letsblockit/letsblockit/blame/main/data/filters/youtube-cleanup.yaml) should help us identify what rules are the oldest and should be removed. Could we focus this PR on the `youtube-cleanup` template only, and discuss the other templates in https://github.com/letsblockit/letsblockit/pull/294?

**Comment by JohnyP36** [comment]
> Heya @JohnyP36 and @BPower0036 . Thank you both for your quick response! It's unfortunate that you duplicated work, and I'm sorry about that!
> 
> I do agree that it's probably better to keep the "old-new" rules for now, as I'm not sure that the new layout has been rolled out to all countries. Checking the [git blame for this file](https://github.com/letsblockit/letsblockit/blame/main/data/filters/youtube-cleanup.yaml) should help us identify what rules are the oldest and should be removed. Could we focus this PR on the `youtube-cleanup` template only, and discuss the other templates in #293?

Yes, that's fine. 
Before removing the old rules, I indeed check the `git blame`, but one is from 5 months ago and the other from 4. 
Up until a week ago I always had the layout from 5 months ago (both when I was logged in to Youtube and when logged out). 
To me it seems that both the 4-and-5-months-ago layouts have been replaced with the new one -- with rounded corners.

**Comment by JohnyP36** [comment]
@xvello I think it's save to merge this PR now without disturbing users that are using those rules, as it seems that the new YT layout has been rolled out to every country.

**Review by xvello — APPROVED** [review]
Thanks @JohnyP36! Sorry for the low responsiveness, life is very busy right now, but it should hopefully settle in a week or two.

**Pull request merged**
