### PR TITLE
aliexpress-stores: add new template to hide results by store name

### LINKED ISSUE #495: Filter Aliexpress search results by store name (regex/glob)
### What website(s) would this filter apply to?

https://aliexpress.com

### What content should be blocked?

Often fake stores will popup and flood Aliexpress search results with dodgy results, the good news is these usually have highly predictable store names.

Using the following filter I can block

### What options should be offered?

A regex or pattern to match for the store names.

A default could be `(/Shop\d+ Store/)` which catches a huge amount of fake generated stores currently flooding the site.

### Did you write a custom uBlock filter already?

Yes!

```
! https://www.aliexpress.com filter out fake generated stores such as "Shop 12345 Store"
www.aliexpress.com##a.search-card-item[class*="cards--gallery--"][class*="manhattan--container--"]:has-text(/Shop\d+ Store/)
```

### Additional notes

Looking at the existing templates, I suspect something like this:

```yaml
title: "AliExpress: filter out results by store name"
contributors:
  - sammcj
params:
  - name: pattern
    description: Regex or patterns to match store names
    type: list
    default: [ "Shop \d+ Store" ]
tags:
  - youtube
template: |
  {{#each pattern}}
  www.aliexpress.com##a.search-card-item[class*="cards--gallery--"][class*="manhattan--container--"]:has-text(/\b{{this}}\b/i)
```

But would need tests etc...

### PR DESCRIPTION
**Pull request by sammcj**
A simple filter to allow the user to remove unwanted stores from AliExpress (e.g. fakes/spammers etc...)

It currently provides filtering based on the store name (e.g. the common pattern of Shop 12345 Store) but could be extended easily enough.

@JonnyP36 and @xvello for their help with this!

Fixes #495

---

One potential improvement might be to look at replacing has-text with a more efficient function (similar to @xvello's comment on another issue here: https://github.com/letsblockit/letsblockit/issues/496#issuecomment-1625133271, and may be aided by the 'wordOrRegex' list variant once ready - https://github.com/letsblockit/letsblockit/pull/352/files)

### CODE REVIEW

**Comment by xvello** [comment]
Heya @sammcj, thanks for your contribution, I'll review it shortly.

I merged https://github.com/letsblockit/letsblockit/pull/498 to add you to the contributors lists, so that the linting passes. I'm happy to change your avatar to your photo if you give me a URL.

**Review by JohnyP36 — APPROVED** [review]
@sammcj Thanks for opening this PR. It pasted all the test, which is good and means the template should work.

**Comment by xvello** [comment]
Heya folks, I took the liberty of doing [the following changes](https://github.com/letsblockit/letsblockit/pull/505/commits/ede1f7ee0c6aa490a35d51578f764b16f27f20cc) before merging:

- pluralize the param name into `shop-names`, as it's a list
- remove the preset and move it into the description instead:
  - a preset comes with a commitment to  maintain and expand it to keep it somewhat exhaustive. I'm doing it for the https://letsblock.it/filters/amazon-products ones, but I don't know whether we want to commit to play a cat-and-mouse game with bad actors
  - a default is difficult to change after people have enabled it, so it's not great either

Happy to have another PR to create the preset if @sammcj is interested in maintaining it though!

**Review by xvello — APPROVED** [review]
Thanks @sammcj for your contribution!

I'd love your feedback on the process and how we can improve it, and of course don't hesitate to suggest other ideas!

**Comment by JohnyP36** [comment]
>  -   a preset comes with a commitment to maintain and expand it to keep it somewhat exhaustive. I'm doing it for the https://letsblock.it/filters/amazon-products ones, but I don't know whether we want to commit to play a cat-and-mouse game with bad actors
> -   a default is difficult to change after people have enabled it, so it's not great either

You are right. Although already merged I agree on your changes.

**Pull request merged**
