### PR TITLE
youtube-cleanup: add mobile rules for more options

### PR DESCRIPTION
**Pull request by JohnyP36**
For some rules there are also alternatives for YouTube Music, as they have different code.  Also for now, all the rules start with `www` and are not applied to `m.youtube.com.` 

I don't now if it's better to start a new template for YouTube Music.

### CODE REVIEW

**Comment by xvello** [comment]
Heya @JohnyP36, thanks for your contribution! Totally worth having in the same template too, as we do for the shorts rules.

My understanding is that `m.youtube.com` is the mobile (phones) version of youtube, and youtube music is hosted at `music.youtube.com`. Do these rules work for regular videos on mobile too?

**Review by xvello — APPROVED** [review]
Thanks a lot!

Have not tested the rules, but they look OK performance-wise, so I'll assume they work fine.
It would be great to eventually have `m.youtube.com` rules for all the options, but we can iterate over several PRs.

**Comment by JohnyP36** [comment]
> Thanks a lot!
> 
> Have not tested the rules, but they look OK performance-wise, so I'll assume they work fine. It would be great to eventually have `m.youtube.com` rules for all the options, but we can iterate over several PRs.

Not all rules for the normal youtube version are applicable on `m.youtube.com` as the mobile version doesn't as much functions or has a different layout so that not all rules for the normal version are needed in the mobile version.

**Comment by xvello** [comment]
> Not all rules for the normal youtube version are applicable on m.youtube.com as the mobile version doesn't as much functions or has a different layout so that not all rules for the normal version are needed in the mobile version.

You are right!

- the following UI elements don't seem to show up on mobile phones (they might show on tablets?): `channel-clarification`, `remove-stream-chat`
- `no-ambient-mode` needs separate work, as I could not write a mobile rule that didn't remove the high CPU overhead. As I wrote in the issue for that option, I think we'd do people a disservice by just hiding it while it burns battery
- `remove-comment-section` and `remove-comments-with-words` could be implemented later if someone requests it. Comments are folded by default, so they're not a big annoyance

**Pull request merged**
